In [5]:
#Q1
def greet(name):
    print(f"Hello,{name}!")

nme=input("enter your name: ")
greet(nme)

enter your name:  sanya


Hello,sanya!


In [6]:
#Q2
def add(a,b):
    return a+b
a=int(input("enter 1st no.: "))
b=int(input("enter 2nd no.: "))
add(a,b)

enter 1st no.:  2
enter 2nd no.:  3


5

In [7]:
#Q3
def check(num):
    if num%2==0:
        print(f"{num} is an even number.")
    else:
        print(f"{num} is an odd number.")

n=int(input("enter a number :"))
check(n)

enter a number : 3


3 is an odd number.


In [3]:
#Q4
def great(a,b,c):
    if a>b and a>c:
        print(f"{a} is greatest")
    elif b>a and b>c:
        print(f"{b} is greatest")
    else:
        print(f"{c} is greatest")

x=int(input("enter 1st number :"))
y=int(input("enter 2nd number :"))
z=int(input("enter 3rd number :"))
great(x,y,z)

enter 1st number : 5
enter 2nd number : 2
enter 3rd number : 8


8 is greatest


In [4]:
#Q5
def reverse(str):
    reversed_str=str[::-1]
    print(f"The reversed string is {reversed_str}.")

word=input("Enter any word: ")
reverse(word)

Enter any word:  sanya


The reversed string is aynas.


In [6]:
#Q6
def factorial(n):
    result=1
    for i in range(1,n+1):
        result*=i
    print(f"Factorial of {n} is {result}.")
num=int(input("Enter any number: "))
factorial(num)

Enter any number:  5


Factorial of 5 is 120.


In [7]:
#Q7
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [11]:
#Q8
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#Q9
random=np.random.randint(1,101,size=5)
print(random)

[ 8 78 86 42 49]


In [16]:
#Q10
a=np.array([10,20,30,40,50])
add=0
for i in a:
    add+=i
print(add)

150


In [17]:
#Q11
arr=np.array([5,10,15])
mean=arr.mean()
print(mean)

10.0


In [18]:
#Q12
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [19]:
#Q13
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [20]:
#Q14
import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [21]:
#Q15
data={'Name':['Alice','Charlie'], 'Age':[25,30]}
dict=pd.DataFrame(data)
print(dict)

      Name  Age
0    Alice   25
1  Charlie   30


In [ ]:
#Q16
df=pd.read_csv("filename.csv")
print(df)

In [22]:
#Q17
data={'Name':['Alice','Charlie'], 'Age':[25,30]}
dict=pd.DataFrame(data)
print(dict['Age'])

0    25
1    30
Name: Age, dtype: int64
