In [4]:
import sqlite3
conn=sqlite3.connect('students.db')

#creating a cursor object
cursor=conn.cursor()
cursor.execute('''
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    grade TEXT
)
''')
conn.commit()
print("Table created successfully")

Table created successfully


In [7]:
def insert_student(name,age,grade):
    conn.execute("INSERT INTO students (name,age,grade) values (?,?,?)",(name,age,grade))
    conn.commit()
    print("Row inserted successfully")

insert_student('Riya',20,'A')
insert_student('Sanya',19,'A')
                 

Row inserted successfully
Row inserted successfully


In [9]:
def fetch_student():
    cursor.execute("SELECT * FROM students")
    rows=cursor.fetchall()
    for row in rows:
        print(row)

fetch_student()
        

(1, 'Riya', 20, 'A')
(2, 'Sanya', 19, 'A')


In [ ]:
def update_student(student_id,name,age,grade):
    cursor.execute("UPDATE students set name,

In [14]:
def delete_student(student_id):
    cursor.execute("DELETE FROM STUDENTS WHERE id=?", (student_id,))
    conn.commit()
    print("Student deleted successfully")

delete_student(2)

Student deleted successfully


In [19]:
import sqlite3

#Database connection
conn=sqlite3.connect('lib.db')
cur=conn.cursor()

#Table create (run once)
cur.execute('''CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    email TEXT,
    pswd TEXT,
    bk_issued TEXT
)
''')
cur.execute('''CREATE TABLE IF NOT EXISTS book (
    bk_id INTEGER PRIMARY KEY AUTOINCREMENT,
    bk_name TEXT,
    bk_price REAL
)
''')
conn.commit()


In [24]:
def login_acc(name,pswd):
    cursor.execute("SELECT * FROM library where name=? and pswd=?",(name,pswd))
    user=fetchone()
    if user:
        print(f"Welcome {user[1]}!!")
        return user
    else:
        print("Invalid username or password")
        return None

In [23]:
def add_book(bk_name,bk_price):
    cursor.execute("INSERT INTO book (bk_name,bk_price) VALUES (?,?,?)",(bk_name,bk_price))
    conn.commit()
    print("Book added successfully")

In [ ]:
def add_user(name,email,pswd):
    cursor.execute("INSERT INTO user (name,email,pswd) VALUES (?,?,?)", (name,email,pswd))
    conn.commit()
    print("User added successfully")

In [1]:
def issue_book(userid,pswd):
    cursor.execute("SELECT * FROM user where userid=? and pswd=?", (userid,pswd))
    user=fetchone()
    if user:
        cursor.execute("UPDATE user SET bk_issued= ?", (name,))
        return user
    else:
        print("Invalid user")
        return None

In [ ]:
def lib_menu():
    print("**********Welcome to Python Library************")
    name=input("enter your name:")
    pswd=input("enter your password:")

    usr=login_acc(name,pswd)
    if not usr:
        return

    while True:
        print("\n--- Menu ---")
        print("1. ADD BOOK")
        print("2. ADD USER")
        print("3. ISSUE BOOKS")
        print("4. EXIT")
        choice=input("enter your choice: ")

        if choice=='1':
            add_book("computer science",1200.00)
        elif choice=='2':
            add_user("sanya","sanyamtwn@gmail.com","snymat")
        elif choice=='3':
            issue_book(3,"snymat")
        else:
            print("

In [27]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [29]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)  # (2,3) (rows,columns)
print(arr.size)   # 6
print(arr.ndim)   # 2
print(arr.dtype)  # int64

(2, 3)
6
2
<U21


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))



[[1 2 3]
 [4 5 6]]
